"""Prometheus metrics collectors and instrumentation for MIRAGE factual consistency verification."""

import time
from collections.abc import Generator
from contextlib import contextmanager

from prometheus_client import (
    CONTENT_TYPE_LATEST,
    REGISTRY,
    CollectorRegistry,
    Counter,
    Gauge,
    Histogram,
    generate_latest,
)

# Core HTTP & Gateway Metrics
REQUESTS_TOTAL = Counter(
    "mirage_requests_total",
    "Total HTTP verification and proxy requests handled by MIRAGE gateway.",
    ["tenant_id", "status_code", "endpoint"],
)

# Latency & Pipeline Step Histograms
VERIFICATION_LATENCY_SECONDS = Histogram(
    "mirage_verification_latency_seconds",
    "End-to-end verification pipeline latency in seconds.",
    ["tenant_id", "tier"],
    buckets=(0.05, 0.1, 0.25, 0.5, 1.0, 2.0, 3.0, 5.0, 10.0),
)

MODULE_LATENCY_SECONDS = Histogram(
    "mirage_module_latency_seconds",
    "Latency of individual verification modules in seconds.",
    ["module"],  # "flan_t5", "rav", "scs", "ics", "nli", "vgs", "hrs_engine", "correction"
    buckets=(0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0, 2.0, 5.0),
)

# HRS & Uncertainty Quantification Histograms
HRS_DISTRIBUTION = Histogram(
    "mirage_hrs_distribution",
    "Distribution of Hallucination Risk Scores (HRS) generated by meta-learner.",
    ["tenant_id", "model_id"],
    buckets=(0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0),
)

HRS_CI_WIDTH = Histogram(
    "mirage_hrs_ci_width",
    "Width of Mondrian conformal prediction confidence intervals.",
    ["tenant_id", "tier"],
    buckets=(0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.4, 0.5),
)

# Hallucination & Risk Tier Counters
HALLUCINATION_TIER_TOTAL = Counter(
    "mirage_hallucination_tier_total",
    "Total verification responses grouped by calibrated risk tier.",
    ["tenant_id", "tier"],  # "LOW", "MEDIUM", "HIGH", "CRITICAL"
)

CORRECTION_TRIGGERED_TOTAL = Counter(
    "mirage_correction_triggered_total",
    "Total agentic correction loops initiated for high/critical hallucination responses.",
    ["tenant_id", "success"],
)

# Cache & Efficiency Counters
SCS_CACHE_HITS_TOTAL = Counter(
    "mirage_scs_cache_hits_total",
    "Total Self-Consistency Sampling (SCS) prompt cache hits.",
    ["tenant_id"],
)

SCS_CACHE_MISSES_TOTAL = Counter(
    "mirage_scs_cache_misses_total",
    "Total Self-Consistency Sampling (SCS) prompt cache misses.",
    ["tenant_id"],
)

# System Gauges
ACTIVE_SESSIONS = Gauge(
    "mirage_active_sessions",
    "Current active concurrent verification sessions.",
    ["tenant_id"],
)

CIRCUIT_BREAKER_STATE = Gauge(
    "mirage_circuit_breaker_state",
    "Circuit breaker status (0 = CLOSED / healthy, 1 = OPEN / failing).",
    ["dependency"],
)

RABBITMQ_QUEUE_DEPTH = Gauge(
    "mirage_rabbitmq_queue_depth",
    "Depth of Celery task queue per worker type.",
    ["worker_type"],
)

CLIP_PREFILTER_PASS_RATE = Gauge(
    "mirage_clip_prefilter_pass_rate",
    "Rolling pass rate of image claims passing the CLIP pre-filter without requiring LLaVA.",
    ["tenant_id"],
)


def record_request_metric(tenant_id: str, status_code: int, endpoint: str) -> None:
    """Increment the HTTP request counter for a given tenant, status code, and endpoint."""
    REQUESTS_TOTAL.labels(
        tenant_id=tenant_id,
        status_code=str(status_code),
        endpoint=endpoint,
    ).inc()


def record_verification_metrics(
    tenant_id: str,
    model_id: str,
    hrs: float,
    tier: str,
    ci_width: float,
    latency_seconds: float,
    cached_scs_hit: bool | None = None,
    correction_applied: bool = False,
    correction_success: bool = False,
) -> None:
    """Record comprehensive telemetry for a completed verification pipeline execution."""
    # Latency & distributions
    VERIFICATION_LATENCY_SECONDS.labels(tenant_id=tenant_id, tier=tier).observe(latency_seconds)
    HRS_DISTRIBUTION.labels(tenant_id=tenant_id, model_id=model_id).observe(hrs)
    HRS_CI_WIDTH.labels(tenant_id=tenant_id, tier=tier).observe(ci_width)

    # Risk tier counter
    HALLUCINATION_TIER_TOTAL.labels(tenant_id=tenant_id, tier=tier).inc()

    # SCS cache metrics
    if cached_scs_hit is True:
        SCS_CACHE_HITS_TOTAL.labels(tenant_id=tenant_id).inc()
    elif cached_scs_hit is False:
        SCS_CACHE_MISSES_TOTAL.labels(tenant_id=tenant_id).inc()

    # Correction loop metrics
    if correction_applied:
        CORRECTION_TRIGGERED_TOTAL.labels(
            tenant_id=tenant_id,
            success=str(correction_success).lower(),
        ).inc()


def record_circuit_breaker_state(dependency: str, is_open: bool) -> None:
    """Update circuit breaker gauge (1 for OPEN, 0 for CLOSED)."""
    CIRCUIT_BREAKER_STATE.labels(dependency=dependency).set(1.0 if is_open else 0.0)


@contextmanager
def time_module(module_name: str) -> Generator[None, None, None]:
    """Context manager measuring execution latency of an internal pipeline module."""
    start_time = time.time()
    try:
        yield
    finally:
        elapsed = time.time() - start_time
        MODULE_LATENCY_SECONDS.labels(module=module_name).observe(elapsed)


def export_metrics(registry: CollectorRegistry = REGISTRY) -> tuple[bytes, str]:
    """Export all registered Prometheus metrics in text exposition format."""
    return generate_latest(registry), CONTENT_TYPE_LATEST
