# Redis configuration for MIRAGE
port 6379
protected-mode no
tcp-backlog 511
timeout 0
tcp-keepalive 300
daemonize no
supervised no
loglevel notice
databases 16
always-show-logo no
save ""
appendonly no

# Load ACL users from file
aclfile /usr/local/etc/redis/users.acl
