"""Shared schema exports."""

from shared.schemas.alerts import (
    AcknowledgeAlertRequest,
    AlertSeverity,
    AlertsListResponse,
    AlertStatus,
    OperatorAlertResponse,
)
from shared.schemas.audit import (
    GENESIS_ROOT_HASH,
    AuditLogEntry,
    TrustedCheckpointRegistry,
    compute_sha256,
    is_valid_sha256_hex,
)
from shared.schemas.auth import ROLE_PERMISSIONS, AuthContext, Permission, Role
from shared.schemas.claims import (
    CRITICALITY_WEIGHTS,
    Claim,
    ClaimCriticality,
    ClaimType,
    ClaimVerificationResult,
    EvidenceChunk,
    VerificationStatus,
)
from shared.schemas.error import ErrorDetail, ErrorEnvelope
from shared.schemas.hrs import (
    ConformalInterval,
    HRSResult,
    RiskTier,
    SignalAttribution,
    determine_risk_tier,
)
from shared.schemas.outcome import (
    ObservabilityClass,
    OutcomeReconciliationRequest,
    OutcomeReconciliationResult,
    OutcomeStatus,
    OutcomeVerificationContract,
    OutcomeVerificationRequest,
    OutcomeVerifierType,
)
from shared.schemas.output import (
    BudgetConsumption,
    CalibrationMetadata,
    Gate4Decision,
    OutputAssuranceContract,
    OutputAssuranceRequest,
    OutputFactualResult,
    OutputSafetyResult,
    OutputVerificationStatus,
    VerificationBudget,
    VerificationTier,
)
from shared.schemas.reports import (
    GenerateReportRequest,
    GenerateReportResponse,
    ReportDetailResponse,
    ReportStatus,
)
from shared.schemas.verification import (
    VerificationMetadata,
    VerificationRequest,
    VerificationResponse,
    VerificationStreamEvent,
)

__all__ = [
    "AuditLogEntry",
    "compute_sha256",
    "GENESIS_ROOT_HASH",
    "is_valid_sha256_hex",
    "TrustedCheckpointRegistry",
    "AuthContext",
    "Role",
    "Permission",
    "ROLE_PERMISSIONS",
    "Claim",
    "ClaimCriticality",
    "ClaimType",
    "ClaimVerificationResult",
    "CRITICALITY_WEIGHTS",
    "EvidenceChunk",
    "VerificationStatus",
    "ConformalInterval",
    "HRSResult",
    "RiskTier",
    "SignalAttribution",
    "determine_risk_tier",
    "VerificationMetadata",
    "VerificationRequest",
    "VerificationResponse",
    "VerificationStreamEvent",
    "AlertStatus",
    "AlertSeverity",
    "OperatorAlertResponse",
    "AcknowledgeAlertRequest",
    "AlertsListResponse",
    "ReportStatus",
    "GenerateReportRequest",
    "GenerateReportResponse",
    "ReportDetailResponse",
    "ErrorDetail",
    "ErrorEnvelope",
    "OutputVerificationStatus",
    "Gate4Decision",
    "VerificationTier",
    "VerificationBudget",
    "BudgetConsumption",
    "CalibrationMetadata",
    "OutputSafetyResult",
    "OutputFactualResult",
    "OutputAssuranceContract",
    "OutputAssuranceRequest",
    "ObservabilityClass",
    "OutcomeStatus",
    "OutcomeVerifierType",
    "OutcomeVerificationRequest",
    "OutcomeVerificationContract",
    "OutcomeReconciliationRequest",
    "OutcomeReconciliationResult",
]
